name = "ronisbr"
uuid = "3f5c9dc5-b22a-4de3-bc35-eaa67c74ee3b"
repo = "https://github.com/ronisbr/Registry.git"
description = "My local Julia registry"

[packages]
7fa26607-a272-47b2-9aa2-a6c1d419d9d2 = { name = "SatelliteToolboxLegendre", path = "S/SatelliteToolboxLegendre" }
